### ISSUE TITLE
Mimic other language client's API

### ISSUE THREAD

**Issue by jacegu** [dnsimple/dnsimple-elixir#10]
The idea is to be able to use the client like this:

```elixir
client = %Client{...}
Dnsimple.zones.list_zones(client, "_")
Dnsimple.zones.list_records(client, "_", "example.com")
```

instead of interacting with the service modules directly.

**Comment by aeden** [comment]
I've been thinking about this a bit and I'm seeing a pattern emerge from my tests which might be useful:

The `Dnsimple.zone` function could be implemented like this:

```elixir
def zones
  Application.get_env(app_name, :dnsimple_zone_service, Dnsimple.ZonesService)
end
```

This way the service can be easily overridden in `config/test.exs` allowing for mocking. Not sure how to get the current `app_name` value, but I am hopeful there's a way.

**Comment by jacegu** [comment]
I'm not sure how I feel about this route yet: I'm all up for [the kind of mocking you are doing](http://blog.plataformatec.com.br/2015/10/mocks-and-explicit-contracts/) but I'm not sure it's the internals of the DNSimple library what should be mocked.

Anyhow, if we go this route, a client of the app should be able to override this in the test config `config/test.exs`, so there is no need to figure out the app name:

```elixir
configure :dnsimple, :dnsimple_zone_service, DummyZonesService
```

**Comment by aeden** [comment]
@jacegu it's a fair point. Maybe for my purpose I'll just continue using a thin wrapper around the DNSimple library and mock the library calls there.
