### ISSUE TITLE
Clarify logger level

### ISSUE THREAD

**Issue by jacegu** [dnsimple/dnsimple-elixir#102]
Newcomers playing with the client will face the debugging output and may find it disturbing. 

It may be a better idea to set the default logging level to `debug` and add a section to the README about managing the logging level (specially so we document that it's available).

**Comment by weppos** [comment]
@jacegu it's not clear to me if right now the client level is debugging or info. You say:

>  will face the debugging output and may find it disturbing.

which seems to indicate the level is debug, but then you mention about setting debug by default.

**Comment by jacegu** [comment]
@weppos I started an app from scratch and installed the client as a dependency. Testing things from the interpreter without touching any configuration will display the logging messages. 

Looking closer at it I think the issue is that the logger app (which is a separate app) defaults to debug level and you have to explicitly configure the level to info in your app's `config/config.exs`:

```elixir
config :logger, level: :info
```

I think adding a note about the logging level in the README is enough to close this.

**Comment by jacegu** [comment]
> I think adding a note about the logging level in the README is enough to close this.

@jodosha @nesQuick @weppos do you agree :point_up: ?

**Comment by nesQuick** [comment]
@jacegu I agree that a note should be sufficient as log levels are a Elixir concept
