### ISSUE TITLE
Dnsimple.Zone.File should be Dnsimple.ZoneFile

### ISSUE THREAD

**Issue by jacegu** [dnsimple/dnsimple-elixir#116]
This is something that I just realized while working on the code base and that I'd like to address. However, since it's a breaking change I want to discuss how to approach it here:

We have:

- `Dnsimple.Zone`
- `Dnsimple.ZoneRecord`
- `Dnsimple.ZoneDistribution`

And then we have:
- `Dnsimple.Zone.File`

I'd like this last one to be changed to `Dnsimple.ZoneFile` for both consistency within this codebase and across other language clients. Do you agree? How do you think we should handle this change?

**Comment by weppos** [comment]
I agree. Is there a way to keep the legacy Zone.File around for the time being, and delegate to the new one (maybe with a warning)?
