### ISSUE TITLE
Should the client be an OTP application?

### ISSUE THREAD

**Issue by jacegu** [dnsimple/dnsimple-elixir#14]
This question comes mostly from my short knowledge of both OTP and Elixir:

While working on a Phoenix app using the client I was facing an odd error that I had to fix by [adding `httpoison` to the list of OTP apps that are started](http://stackoverflow.com/questions/31208923/hackney-fails-to-make-request-to-server) along the web app. I replaced `httpoison` with `dnsimple` so both the `logger` and the `httpoison` apps that [our client depends on](https://github.com/aetrion/dnsimple-elixir/blob/master/mix.exs#L19) are started.

In my head I was envisioning this as a plain old library that could be used inside an OTP application letting the customers decide how to structure the corresponding processes and such but since we depend on `httpoison` this may not be possible... 

Is there a way around it or is this the way it should be?

**Comment by aeden** [comment]
I think having it as an OTP application is fine. There really is no downside.
