### ISSUE TITLE
Add auto-pagination support

### ISSUE THREAD

**Issue by jacegu** [dnsimple/dnsimple-elixir#35]
We have to:
- [x] Parse and expose pagination data
- [x] Extract helper functions to automatically go through all the pages

These are the endpoints that are missing the pagination function:
- [x] `Domains`. See #36
- [ ] `Contacts`.
- [ ] `Zones`.
- [ ] `ZoneRecords`.
- [ ] `Services`.
- [ ] `DomainServices` (`appliedServices`).
- [ ] `Certificates`.
- [ ] `Pushes`.
- [ ] `Templates`.
- [ ] `TLDs`.
- [x] ~~`Webhooks`~~ (Not paginated)

**Comment by aeden** [comment]
@jacegu it looks like the library does not parse and provide access to the pagination portion of the response, does it?

**Comment by jacegu** [comment]
No it does not. We do have the rate limiting data parsed an exposed as part of the response.

**Comment by aeden** [comment]
The `all_domains` function (and any other `all_` function) should return a tuple. Thus, if the domain list was successfully compiled with no errors, then it should return `{:ok, [Domain.t]}`. The same rule should apply to every `all_` function.

Optionally we can provide ! versions that return the domain list and raise an exception if we are inclined to do so.

**Comment by jacegu** [comment]
I think the `all_*` functions should:

- Return `{:ok, list}` if the requests of all pages were successful. The `list` term of the tuple will be the list with the resources of all pages.
- Return `{:error, response}` if the request of any page fails. The `response` term of the tuple will be the response that failed.

Does this sound ok @aeden ?

**Comment by aeden** [comment]
I agree that it should return a tuple.
