### ISSUE TITLE
Attributes can be a Keyword or a Map

### ISSUE THREAD

**Issue by jacegu** [dnsimple/dnsimple-elixir#43]
There is some sort of bug preventing us from using a `Keyword` to represent the arguments in `POST`, `PUT` and `PATCH` requests:

```
iex(4)> Dnsimple.Zones.create_record(client, 63, "xxx0002test.com", type: "ALIAS", content: "myapp.herokapp.com", ttl: 600)
** (Poison.EncodeError) unable to encode value: {:ttl, 600}
               lib/poison/encoder.ex:346: Poison.Encoder.Any.encode/2
               lib/poison/encoder.ex:232: anonymous fn/3 in Poison.Encoder.List.encode/3
               lib/poison/encoder.ex:233: Poison.Encoder.List."-encode/3-lists^foldr/2-1-"/3
               lib/poison/encoder.ex:233: Poison.Encoder.List.encode/3
               lib/poison.ex:41: Poison.encode!/2
    (dnsimple) lib/dnsimple.ex:246: Dnsimple.Client.process_request_body/2
    (dnsimple) lib/dnsimple.ex:199: Dnsimple.Client.execute2/5
    (dnsimple) lib/dnsimple/zones.ex:56: Dnsimple.Zones.create_record/5
```

Looks like it only works when attributes are represented as a map:

```
iex(4)> Dnsimple.Zones.create_record(client, 63, "xxx0002test.com", %{type: "ALIAS", content: "myapp.herokapp.com", ttl: 600})
{:error,
 %Dnsimple.RequestError{http_response: %HTTPoison.Response{body: "{\"message\":\"Validation failed\",\"errors\":{\"name\":[\"can't be nil\"]}}",
   headers: [{"Server", "nginx"}, {"Date", "Fri, 02 Sep 2016 08:55:58 GMT"},
    {"Content-Type", "application/json; charset=utf-8"},
    {"Transfer-Encoding", "chunked"}, {"Connection", "keep-alive"},
    {"X-RateLimit-Limit", "2400"}, {"X-RateLimit-Remaining", "2398"},
    {"X-RateLimit-Reset", "1472810100"}, {"Cache-Control", "no-cache"},
    {"X-Request-Id", "f997b61c-0887-4253-8358-1cf1914818dd"},
    {"X-Runtime", "0.116337"}, {"X-Content-Type-Options", "nosniff"},
    {"X-Download-Options", "noopen"}, {"X-Frame-Options", "DENY"},
    {"X-Permitted-Cross-Domain-Policies", "none"},
    {"X-XSS-Protection", "1; mode=block"}], status_code: 400},
  message: "HTTP 400: Validation failed"}}
```

**Comment by weppos** [comment]
@jacegu I think this is expected, I believe HTTPoison required a Map.

**Comment by aeden** [comment]
When I was using functions like this I am always passing a `%Dnsimple.ZoneRecord{}` struct. I don't think I ever expected to be able to use a keyword list.

**Comment by weppos** [comment]
I agree with @aeden. A keyword list can also have key duplicates, which is not really what we want. I think it's safe to assume/document that the parameters must be a map (or a Struct which is basically backed by a map).

**Comment by jacegu** [comment]
This also affects other payloads that are not represented by an Elixir `Record`, e.g:

```elixir
Dnsimple.Registrar.register_domain(client, account_id, registrant_id: 123, auto_renewal: true)
```

I think it's nice to accept both a `Record` and a `Keyword`. I will verify what happens with duplicate keys when you transform the `Keyword` into a `Map` and propose a solution.

**Comment by weppos** [comment]
@jacegu FYI when I originally structured the client, I only conceived

    Dnsimple.Registrar.register_domain(client, account_id, %{ registrant_id: 123, auto_renewal: true })

hence I'm fine to not support Keyword lists. In fact, I think we should not as even if we happen to encode them properly, the risk of having duplicate keys is present and it may lead to subtle bugs.

I think whoever calls the client should be responsible of properly converting the argument.

Actually, I was not even aware of that syntax for the Keyword list, I've been used to see it as:

    [{:a, 1}, {:b, 2}]

**Comment by jacegu** [comment]
FWIW:

```
iex(9)> Enum.into([a: 1, b: 2, c: 3, a: 1, c: 3], %{})
%{a: 1, b: 2, c: 3}
```

**Comment by weppos** [comment]
@jacegu but what if someone for whatever reason passes:

    [name: "example.com", ..., name: "example.net"]

Which one should we take? Frankly, I feel that whatever decision we make (first win, last win), we leave it open for bugs.

**Comment by jacegu** [comment]
```
iex(10)> Enum.into([a: 1, b: 2, c: 3, a: 4, c: 5], %{})
%{a: 4, b: 2, c: 5}
```

**Comment by aeden** [comment]
@jacegu you appear to be trying hard to justify using keyword arguments. Since we define the argument type, what benefit do we realize by supporting them that we otherwise do not have with just maps?

**Comment by jacegu** [comment]
It's simply a matter of syntax... Being a Rubyist is also something I'd expect. Having to pass in a map even for 1 single key-value pair feels very ugly to me 😕

**Comment by weppos** [comment]
In Ruby you don't have Keyword lists, what you are actually passing when you use the syntax you proposed is a `Hash`.

Frankly, I feel that we should avoid to support a Keyword list, we just open more space to subtle bugs.

**Comment by jacegu** [comment]
FWIW in Ruby you have the same behaviour (the only difference is a warning):

```
irb(main):001:0> def function(arg, options)
irb(main):002:1> puts arg
irb(main):003:1> puts options
irb(main):004:1> end
=> :function
irb(main):005:0> function("arg", a: 1, b: 2, c: 3, a: 4, c: 5)
(irb):5: warning: key :a is duplicated and overwritten on line 8
(irb):5: warning: key :c is duplicated and overwritten on line 8
arg
{:a=>4, :b=>2, :c=>5}
=> nil

**Comment by weppos** [comment]
@jacegu your comparison with Ruby is incorrect to me. In Ruby

    method(foo: "bar")
    method({ foo: "bar" })

are interchangeable, because they both represent an Hash. In Elixir is not, as a language decision the former is the syntax of a Keyword list. Therefore, I vote 👎  to support it right now as I feel:

- we are cargo culting Ruby
- we may open the door to subtle bug

The issue is potentially even more confusing, if you consider that it may lead to potential limitations if we decide to perform some pattern matching on the input (doing pattern matching on a Keyword list is harder than a Map).

Pretty much every where I see that a Keyword list is suggested _assuming_ you may expect duplicate keys, which is clearly not the case here. I often saw the unique key as a common denominator to determine whether a Map is preferred over a Keyword.

Given also supporting Keyword list is not free (as it will potentially require us to introduce a filter layer between our code and Poison), my proposal is to not do it today and (perhaps) reconsider it in the future if we should have a reasonable demanding for it.

Most of the time (unless when writing examples) you may end up working with Struct or Maps, therefore I have the feeling we would introduce an unnecessary complexity by supporting both. I'd like to get more real world feedback before taking this decision.

**Comment by jacegu** [comment]
Given what's been said here I'm changing the label to enhancement.

I honestly think this is a must and that we should support it, but won't fight more over it now as I rather focus on completing the client.

**Comment by weppos** [comment]
We don't need to add this for now.
