### ISSUE TITLE
Define aliases for listing and getting functions

### ISSUE THREAD

**Issue by jacegu** [dnsimple/dnsimple-elixir#44]
For example:

- `Dnsimple.Domains.domains`
- `Dnsimple.Domains.domain`

Will have the aliases:

- `Dnsimple.Domains.list_domains`
- `Dnsimple.Domains.get_domain`

**Comment by aeden** [comment]
@jacegu would you mind flipping it around so the function is named `list_domains` and the alias is `domains`? Same for `get_domain` and `domain`.

**Comment by jacegu** [comment]
@aeden that's fine.

One thing to clarify: I was planning on adding the aliases after the next release (0.9.0 most likely), is that ok with you?

**Comment by aeden** [comment]
@jacegu that's fine.
