### ISSUE TITLE
Rename registrar `AuthInfo` into `AuthCode`

### ISSUE THREAD

**Issue by weppos** [dnsimple/dnsimple-elixir#79]

**Comment by jacegu** [comment]
Without more context I guess you are referring to the parameter for the [transfer domain endpoint](https://developer.dnsimple.com/v2/registrar/#transfer). Since this is provided by client code the only thing to do is update the tests and docs.

Anything I'm missing?

**Comment by jacegu** [comment]
@weppos :point_up:

**Comment by weppos** [comment]
@jacegu sorry, I was supposed to follow up and add a link to our internal ticket, but I did not.

Your assumption is correct.
