### ISSUE TITLE
Check if dnsimple application is running

### ISSUE THREAD

**Issue by OleMchls** [dnsimple/dnsimple-elixir#83]
Because if it's not running but you try to access a resource you only see a hackney error, it's hard to debug what the actual error is.

**Comment by aeden** [comment]
Is there a way to ensure it is always started whenever the library is used?

**Comment by nesQuick** [comment]
Hmm, while I was creating the issue I thought on using `Application.ensure_started/2`[1](http://elixir-lang.org/docs/stable/elixir/Application.html#ensure_started/2) but calling that at every call might be a bit cluttering maybe doing it before calling hackney so somewhere in `Dnsimple.Client.execute/5`

**Comment by jacegu** [comment]
The need to start the `dnsimple` application comes exactly from the fact that it felt wrong to require library users to start `hackney`: they should start our app and not `hackney`. In turn `hackney` didn't have any check in place like the one described here, which makes me think that we shouldn't add one... However I do agree that we should try to make this error better if we can.

Note that we have also documented the requirement to start the app in the README.

**Comment by nesQuick** [comment]
> Note that we have also documented the requirement to start the app in the README.

This is already documented. I just oversaw it. After spending more time around with this, I think it's ok to leave it like this, because it's Elixir default that you add applications you install via mix to your applications list. Also most other hex packages doesn't have a check for this.

**Comment by jacegu** [comment]
BTW I had a brain-fart: every time I said `hackney` I meant `HTTPoison` (which is an Elixir wrapper for `hackney`).

**Comment by jacegu** [comment]
Closing as stale. There was also an agreement that this may not be required.
