### ISSUE TITLE
Return dates as Elixir dates

### ISSUE THREAD

**Issue by OleMchls** [dnsimple/dnsimple-elixir#84]
At the moment dates (in the domains list) return a string `expires_on: "2017-05-15"` I would love to have a actual [Elixir date](https://hexdocs.pm/elixir/Date.html#content).

**Comment by jodosha** [comment]
@nesQuick We left them intentionally as strings across all the clients. The plan is to enhance on a client basis the data, according to the the types that a given language offers.

**Comment by nesQuick** [comment]
refs https://github.com/devinus/poison/issues/106

**Comment by jacegu** [comment]
Closing as stale, we can reconsider this in the future.
